<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>ConNCW.Cli</RootNamespace>
    <AssemblyName>conncw</AssemblyName>

    <!-- Options de publication autonome (à activer via dotnet publish -p:PublishAot=true si besoin) -->
    <InvariantGlobalization>true</InvariantGlobalization>
    <SelfContained>false</SelfContained>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ConNCW.Core\ConNCW.Core.csproj" />
  </ItemGroup>

</Project>
